### ISSUE TITLE
No sound playing on Windows 10

### ISSUE THREAD

**Issue by moiseshorta** [jeonghopark/SketchSynth-Simple#1]
Hi, I just downloaded your software and I'm running Windows 10 Home.

I can get my picture to load but I cannot get any sound output from the software.

I have made sure the volume is up, but it's not working at all.

Maybe there's something I need to do?

Thanks!

**Comment by jeonghopark** [comment]
Hi! thank you for your report. The sound issue of Windows 10 is not a common problem. 
I will check.

**Comment by jeonghopark** [comment]
@moiseshorta Hi! Could you test please this version?
[SketchSynth_Simple-win-setaudiodevice.zip](https://github.com/jeonghopark/SketchSynth-Simple/files/4171310/SketchSynth_Simple-win-setaudiodevice.zip)

**Comment by jeonghopark** [comment]
@moiseshorta Hi! check the new version. You can choose audio interfaces. https://github.com/jeonghopark/SketchSynth-Simple/releases/tag/v0.0.2

**Comment by moiseshorta** [comment]
Hey Jeong, I have just tried this build and the .exe is not even opening up.

**Comment by jeonghopark** [comment]
@moiseshorta It's weird. :-( Someone has tested already. Is that a security issue?
